### ISSUE TITLE
Best Kernel error

### ISSUE THREAD

**Issue by deadman96385** [cybojenix/random-scripts#2]
This happens when i am searching for a tag on the msm-3.10 kernel

https://github.com/arter97/caf_msm-3.10

best_kernel -j8 *-8x16.0

`number of tags to check: 837
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/1TB_HDD/Sean/caf/t560nu/best_kernel", line 71, in background
    print("%s has %d lines changed" % (tn, tc))
TypeError: %d format: a number is required, not NoneType`

**Comment by cybojenix** [comment]
I've not at a pc with the caf sources on at the moment. can you try running it with `-s` please?

**Comment by deadman96385** [comment]
That lets it run farther but then at the end i get this when its mean't to say the best  one

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/1TB_HDD/Sean/caf/t560nu/best_kernel", line 79, in background
    print("Lines changed: %d" % best)
TypeError: %d format: a number is required, not NoneType
```

**Comment by cybojenix** [comment]
Can you run this version, but without `-s` please?
https://raw.githubusercontent.com/cybojenix/random-scripts/5347c1f334c152e2ce04e065abe4ca03a2789560/best_kernel

It'll still error, but it'll give me some useful output

**Comment by deadman96385** [comment]
It seems to be going through the tags till it errors i removed all the lines in between so you can see the start and beginning 

```
`steve@sspencer10:/1TB_HDD/Sean/caf/caf_msm-3.10$ /1TB_HDD/Sean/caf/t560nu/best_kernel -j8 LA.BR.*-8x16.0
number of tags to check: 450
 46090 files changed, 18564402 deletions(-)

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/1TB_HDD/Sean/caf/t560nu/best_kernel", line 72, in background
    print("%s has %d lines changed" % (tn, tc))
TypeError: %d format: a number is required, not NoneType
 46074 files changed, 18558523 deletions(-)

 46090 files changed, 18567316 deletions(-)

 46065 files changed, 18556592 deletions(-)

 46074 files changed, 18559059 deletions(-)

 46090 files changed, 18567674 deletions(-)

 46060 files changed, 18552484 deletions(-)

 46061 files changed, 18554449 deletions(-)

 46090 files changed, 18564402 deletions(-)

 46075 files changed, 18558958 deletions(-)

 46090 files changed, 18567343 deletions(-)

 46065 files changed, 18556611 deletions(-)

 46075 files changed, 18559585 deletions(-)

 46090 files changed, 18567748 deletions(-)

 46060 files changed, 18553427 deletions(-)

 46061 files changed, 18554357 deletions(-)

 46090 files changed, 18565093 deletions(-)

 46076 files changed, 18559303 deletions(-)

 46090 files changed, 18567339 deletions(-)

 46065 files changed, 18556611 deletions(-)

 46076 files changed, 18560017 deletions(-)

 46090 files changed, 18567862 deletions(-)

 46061 files changed, 18554431 deletions(-)

 46061 files changed, 18554138 deletions(-)

 46090 files changed, 18565084 deletions(-)

 46072 files changed, 18555906 deletions(-)

 46090 files changed, 18567454 deletions(-)

 46065 files changed, 18556640 deletions(-)

 46090 files changed, 18567919 deletions(-)

 46076 files changed, 18560094 deletions(-)

 46061 files changed, 18554494 deletions(-)

 46065 files changed, 18556487 deletions(-)

 46090 files changed, 18565092 deletions(-)

 46073 files changed, 18557068 deletions(-)

 46090 files changed, 18567554 deletions(-)

 46065 files changed, 18556671 deletions(-)

 46090 files changed, 18567928 deletions(-)

 46078 files changed, 18560922 deletions(-)

 46064 files changed, 18555097 deletions(-)

 46061 files changed, 18554403 deletions(-)

 46074 files changed, 18558238 deletions(-)

 46090 files changed, 18565597 deletions(-)

 46090 files changed, 18567543 deletions(-)

 46066 files changed, 18557108 deletions(-)

 46090 files changed, 18567932 deletions(-)

 46078 files changed, 18560954 deletions(-)

 46073 files changed, 18556496 deletions(-)

 46064 files changed, 18554901 deletions(-)

 46074 files changed, 18558260 deletions(-)

 46090 files changed, 18565597 deletions(-)

 46090 files changed, 18567539 deletions(-)

 46066 files changed, 18557108 deletions(-)

 46090 files changed, 18567932 deletions(-)

 46078 files changed, 18561037 deletions(-)

 46073 files changed, 18557427 deletions(-)

 46061 files changed, 18554403 deletions(-)

 46074 files changed, 18558373 deletions(-)

 46090 files changed, 18565596 deletions(-)

 46090 files changed, 18567553 deletions(-)

 46066 files changed, 18557119 deletions(-)

 46090 files changed, 18567932 deletions(-)

 46078 files changed, 18561073 deletions(-)

 46074 files changed, 18558601 deletions(-)

 46061 files changed, 18554448 deletions(-)

 46090 files changed, 18566740 deletions(-)

 46074 files changed, 18558479 deletions(-)

 46090 files changed, 18567572 deletions(-)

 46066 files changed, 18557142 deletions(-)

 46078 files changed, 18561157 deletions(-)

 46090 files changed, 18567941 deletions(-)

 46074 files changed, 18558730 deletions(-)

 46064 files changed, 18554901 deletions(-)

 46090 files changed, 18566740 deletions(-)

 46075 files changed, 18558914 deletions(-)

 46090 files changed, 18567587 deletions(-)

 46077 files changed, 18558984 deletions(-)

 46078 files changed, 18561157 deletions(-)

 46090 files changed, 18567941 deletions(-)

 46076 files changed, 18559428 deletions(-)

 46064 files changed, 18554901 deletions(-)

 46090 files changed, 18566835 deletions(-)

 46076 files changed, 18559259 deletions(-)

 46090 files changed, 18567588 deletions(-)

 46077 files changed, 18559110 deletions(-)

 46078 files changed, 18561158 deletions(-)

 46090 files changed, 18567942 deletions(-)

 46087 files changed, 18562378 deletions(-)

 46061 files changed, 18554357 deletions(-)

 46090 files changed, 18566835 deletions(-)

 46076 files changed, 18559533 deletions(-)

 46090 files changed, 18567592 deletions(-)

 46077 files changed, 18559386 deletions(-)

 46078 files changed, 18561158 deletions(-)

 46090 files changed, 18567942 deletions(-)

 46087 files changed, 18562427 deletions(-)

 46064 files changed, 18554955 deletions(-)

 46090 files changed, 18567057 deletions(-)

 46078 files changed, 18560384 deletions(-)

 46090 files changed, 18567642 deletions(-)

 46077 files changed, 18559382 deletions(-)

 46090 files changed, 18567944 deletions(-)

 46078 files changed, 18561223 deletions(-)

 46087 files changed, 18562479 deletions(-)

 46065 files changed, 18556470 deletions(-)

 46090 files changed, 18567115 deletions(-)

 46064 files changed, 18555010 deletions(-)

 46090 files changed, 18567674 deletions(-)

 46078 files changed, 18560373 deletions(-)

 46078 files changed, 18561223 deletions(-)

 46090 files changed, 18568503 deletions(-)

 46087 files changed, 18562428 deletions(-)

 46074 files changed, 18558523 deletions(-)

 46090 files changed, 18567120 deletions(-)

 46065 files changed, 18556582 deletions(-)

 46090 files changed, 18567674 deletions(-)

 46076 files changed, 18559261 deletions(-)

 46090 files changed, 18565093 deletions(-)

 46074 files changed, 18558744 deletions(-)

 46090 files changed, 18564401 deletions(-)

 46064 files changed, 18554967 deletions(-)

 46091 files changed, 18565376 deletions(-)

 46091 files changed, 18566065 deletions(-)

 46090 files changed, 18565299 deletions(-)

 46090 files changed, 18567316 deletions(-)

 46100 files changed, 18570076 deletions(-)

 46074 files changed, 18558733 deletions(-)

 46075 files changed, 18559220 deletions(-)

 46073 files changed, 18557580 deletions(-)

 46091 files changed, 18565400 deletions(-)

 46090 files changed, 18565093 deletions(-)

 46090 files changed, 18565306 deletions(-)

 46090 files changed, 18567340 deletions(-)

 46100 files changed, 18570346 deletions(-)

 46074 files changed, 18558740 deletions(-)

 46075 files changed, 18559220 deletions(-)

 46073 files changed, 18557580 deletions(-)

 46091 files changed, 18565391 deletions(-)

 46090 files changed, 18565093 deletions(-)

 46090 files changed, 18565318 deletions(-)

 46090 files changed, 18567554 deletions(-)

 46100 files changed, 18570346 deletions(-)

 46074 files changed, 18558787 deletions(-)

 46075 files changed, 18559226 deletions(-)

 46073 files changed, 18557667 deletions(-)

 46091 files changed, 18565500 deletions(-)

 46090 files changed, 18565093 deletions(-)

 46090 files changed, 18565395 deletions(-)

 46090 files changed, 18567543 deletions(-)

 46100 files changed, 18570404 deletions(-)

 46074 files changed, 18558903 deletions(-)

 46075 files changed, 18559262 deletions(-)

 46073 files changed, 18557819 deletions(-)

 46091 files changed, 18565600 deletions(-)

 46090 files changed, 18565084 deletions(-)

 46090 files changed, 18565410 deletions(-)

 46090 files changed, 18567543 deletions(-)

 46100 files changed, 18570404 deletions(-)

 46074 files changed, 18558954 deletions(-)

 46075 files changed, 18559263 deletions(-)

 46073 files changed, 18557916 deletions(-)

 46091 files changed, 18565616 deletions(-)

 46090 files changed, 18565084 deletions(-)

 46090 files changed, 18565411 deletions(-)

 46090 files changed, 18567572 deletions(-)

 46100 files changed, 18570404 deletions(-)

 46074 files changed, 18558981 deletions(-)

 46073 files changed, 18557424 deletions(-)

 46074 files changed, 18558139 deletions(-)

 46091 files changed, 18565616 deletions(-)

 46090 files changed, 18565411 deletions(-)

 46090 files changed, 18565087 deletions(-)

 46090 files changed, 18567572 deletions(-)

 46100 files changed, 18570420 deletions(-)

 46074 files changed, 18558996 deletions(-)

 46073 files changed, 18557424 deletions(-)

 46074 files changed, 18558153 deletions(-)

 46091 files changed, 18565646 deletions(-)

 46090 files changed, 18565415 deletions(-)

 46090 files changed, 18565145 deletions(-)

 46090 files changed, 18567592 deletions(-)

 46100 files changed, 18570420 deletions(-)

 46074 files changed, 18558996 deletions(-)

 46073 files changed, 18557424 deletions(-)

 46074 files changed, 18558153 deletions(-)

 46091 files changed, 18565646 deletions(-)

 46090 files changed, 18565416 deletions(-)

 46090 files changed, 18565226 deletions(-)

 46090 files changed, 18567675 deletions(-)

 46100 files changed, 18570425 deletions(-)

 46074 files changed, 18558996 deletions(-)

 46073 files changed, 18557424 deletions(-)

 46074 files changed, 18559059 deletions(-)

 46091 files changed, 18565646 deletions(-)

 46090 files changed, 18565780 deletions(-)

 46090 files changed, 18565299 deletions(-)

 46090 files changed, 18567675 deletions(-)

 46100 files changed, 18570433 deletions(-)

 46075 files changed, 18559206 deletions(-)

 46073 files changed, 18557471 deletions(-)

 46087 files changed, 18562464 deletions(-)

 46091 files changed, 18565646 deletions(-)

 46090 files changed, 18566743 deletions(-)

 46090 files changed, 18565299 deletions(-)

 46090 files changed, 18567737 deletions(-)

 46074 files changed, 18558641 deletions(-)

 46075 files changed, 18559206 deletions(-)

 46090 files changed, 18564483 deletions(-)

 46073 files changed, 18557521 deletions(-)

 46091 files changed, 18565665 deletions(-)

 46090 files changed, 18566743 deletions(-)

 46090 files changed, 18565295 deletions(-)

 46090 files changed, 18567737 deletions(-)

 46074 files changed, 18558672 deletions(-)

 46075 files changed, 18559219 deletions(-)

 46090 files changed, 18564484 deletions(-)

 46073 files changed, 18557521 deletions(-)

 46091 files changed, 18565714 deletions(-)

 46090 files changed, 18566806 deletions(-)

 46090 files changed, 18565289 deletions(-)

 46090 files changed, 18567948 deletions(-)

 46074 files changed, 18558675 deletions(-)

 46075 files changed, 18559222 deletions(-)

 46090 files changed, 18565159 deletions(-)

 46073 files changed, 18557528 deletions(-)

 46091 files changed, 18565715 deletions(-)

 46090 files changed, 18566885 deletions(-)

 46090 files changed, 18565306 deletions(-)

 46074 files changed, 18558675 deletions(-)

 46090 files changed, 18567554 deletions(-)

 46075 files changed, 18559222 deletions(-)

 46090 files changed, 18565159 deletions(-)

 46073 files changed, 18557551 deletions(-)

 46091 files changed, 18566047 deletions(-)

 46090 files changed, 18567205 deletions(-)

 46090 files changed, 18565305 deletions(-)

 46100 files changed, 18569893 deletions(-)

 46074 files changed, 18558675 deletions(-)

 46075 files changed, 18559222 deletions(-)

 46090 files changed, 18565239 deletions(-)

 46073 files changed, 18557551 deletions(-)

 46090 files changed, 18565261 deletions(-)

 46100 files changed, 18568473 deletions(-)

 46090 files changed, 18566730 deletions(-)

 46168 files changed, 18592404 deletions(-)

 46146 files changed, 18588329 deletions(-)

 46150 files changed, 18589761 deletions(-)

 46146 files changed, 18588270 deletions(-)

 46177 files changed, 18601203 deletions(-)

 46090 files changed, 18565278 deletions(-)

 46100 files changed, 18568493 deletions(-)

 46081 files changed, 18558220 deletions(-)

 46168 files changed, 18592497 deletions(-)

 46149 files changed, 18589418 deletions(-)

 46150 files changed, 18589890 deletions(-)

 46146 files changed, 18588270 deletions(-)

 46177 files changed, 18601269 deletions(-)

 46100 files changed, 18567766 deletions(-)

 46100 files changed, 18568531 deletions(-)

 46102 files changed, 18565769 deletions(-)

 46161 files changed, 18592319 deletions(-)

 46168 files changed, 18592497 deletions(-)

 46150 files changed, 18589879 deletions(-)

 46146 files changed, 18588270 deletions(-)

 46178 files changed, 18601923 deletions(-)

 46100 files changed, 18567783 deletions(-)

 46100 files changed, 18568539 deletions(-)

 46094 files changed, 18563240 deletions(-)

 46149 files changed, 18589545 deletions(-)

 46168 files changed, 18592550 deletions(-)

 46162 files changed, 18592780 deletions(-)

 46146 files changed, 18588272 deletions(-)

 46178 files changed, 18601913 deletions(-)

 46100 files changed, 18567940 deletions(-)

 46100 files changed, 18568539 deletions(-)

 46112 files changed, 18571128 deletions(-)

 46149 files changed, 18589608 deletions(-)

 46168 files changed, 18592779 deletions(-)

 46162 files changed, 18592780 deletions(-)

 46146 files changed, 18588409 deletions(-)

 46178 files changed, 18601984 deletions(-)

 46100 files changed, 18567946 deletions(-)

 46100 files changed, 18568539 deletions(-)

 46128 files changed, 18576227 deletions(-)

 46154 files changed, 18588864 deletions(-)

 46168 files changed, 18592777 deletions(-)

 46147 files changed, 18588618 deletions(-)

 46162 files changed, 18592782 deletions(-)

 46178 files changed, 18602081 deletions(-)

 46100 files changed, 18568087 deletions(-)

 46100 files changed, 18568539 deletions(-)

 46094 files changed, 18563240 deletions(-)

 46154 files changed, 18588903 deletions(-)

 46168 files changed, 18592889 deletions(-)

 46147 files changed, 18588618 deletions(-)

 46162 files changed, 18592782 deletions(-)

 46178 files changed, 18602161 deletions(-)

 46100 files changed, 18568087 deletions(-)

 46100 files changed, 18568560 deletions(-)

 46133 files changed, 18577613 deletions(-)

 46169 files changed, 18593161 deletions(-)

 46154 files changed, 18589006 deletions(-)

 46152 files changed, 18592428 deletions(-)

 46162 files changed, 18592814 deletions(-)

 46178 files changed, 18602190 deletions(-)

 46100 files changed, 18568082 deletions(-)

 46100 files changed, 18568560 deletions(-)

 46142 files changed, 18586221 deletions(-)

 46154 files changed, 18589006 deletions(-)

 46169 files changed, 18593167 deletions(-)

 46145 files changed, 18589448 deletions(-)

 46162 files changed, 18592839 deletions(-)

 46179 files changed, 18602281 deletions(-)

 46100 files changed, 18568076 deletions(-)

 46100 files changed, 18568561 deletions(-)

 46142 files changed, 18586638 deletions(-)

 46154 files changed, 18589078 deletions(-)

 46157 files changed, 18595292 deletions(-)

 46169 files changed, 18593262 deletions(-)

 46162 files changed, 18592842 deletions(-)

 46179 files changed, 18602281 deletions(-)

 46100 files changed, 18568103 deletions(-)

 46100 files changed, 18568561 deletions(-)

 46146 files changed, 18587571 deletions(-)

 46162 files changed, 18596659 deletions(-)

 46154 files changed, 18589227 deletions(-)

 46169 files changed, 18593265 deletions(-)

 46162 files changed, 18592842 deletions(-)

 46178 files changed, 18603199 deletions(-)

 46100 files changed, 18568242 deletions(-)

 46100 files changed, 18568550 deletions(-)

 46146 files changed, 18587887 deletions(-)

 46164 files changed, 18597974 deletions(-)

 46169 files changed, 18593265 deletions(-)

 46154 files changed, 18589230 deletions(-)

 46163 files changed, 18593052 deletions(-)

 46179 files changed, 18603554 deletions(-)

 46100 files changed, 18568243 deletions(-)

 46090 files changed, 18565010 deletions(-)

 46146 files changed, 18587887 deletions(-)

 46164 files changed, 18597980 deletions(-)

 46154 files changed, 18589332 deletions(-)

 46169 files changed, 18593325 deletions(-)

 46163 files changed, 18593053 deletions(-)

 46179 files changed, 18603550 deletions(-)

 46100 files changed, 18568451 deletions(-)

 46090 files changed, 18565469 deletions(-)

 46146 files changed, 18588272 deletions(-)

 46164 files changed, 18598032 deletions(-)

 46163 files changed, 18593119 deletions(-)

 46169 files changed, 18593329 deletions(-)

 46154 files changed, 18589331 deletions(-)

 46179 files changed, 18603708 deletions(-)

 46100 files changed, 18568451 deletions(-)

 46090 files changed, 18566544 deletions(-)

 46146 files changed, 18588272 deletions(-)

 46165 files changed, 18598369 deletions(-)

 46150 files changed, 18589761 deletions(-)

 46146 files changed, 18588270 deletions(-)

 46154 files changed, 18589356 deletions(-)

 46179 files changed, 18603679 deletions(-)

 46179 files changed, 18603737 deletions(-)

 46182 files changed, 18604755 deletions(-)

 46182 files changed, 18604836 deletions(-)

 46257 files changed, 18660359 deletions(-)

 46257 files changed, 18660157 deletions(-)

 46257 files changed, 18660511 deletions(-)

 46182 files changed, 18604622 deletions(-)

 46182 files changed, 18604820 deletions(-)

 46261 files changed, 18661303 deletions(-)

 46182 files changed, 18604836 deletions(-)

 46257 files changed, 18660226 deletions(-)

 46257 files changed, 18660510 deletions(-)

 46182 files changed, 18604622 deletions(-)

 46182 files changed, 18604820 deletions(-)

 46270 files changed, 18700076 deletions(-)

 46257 files changed, 18660257 deletions(-)

 46182 files changed, 18604837 deletions(-)

 46257 files changed, 18661229 deletions(-)

 46182 files changed, 18604622 deletions(-)

 46182 files changed, 18604824 deletions(-)

 46277 files changed, 18708677 deletions(-)

 46257 files changed, 18660301 deletions(-)

 46182 files changed, 18604837 deletions(-)

 46257 files changed, 18661281 deletions(-)

 46182 files changed, 18604642 deletions(-)

 46182 files changed, 18604824 deletions(-)

 46278 files changed, 18709146 deletions(-)

 46257 files changed, 18660321 deletions(-)

 46182 files changed, 18605375 deletions(-)

 46257 files changed, 18661240 deletions(-)

 46182 files changed, 18604622 deletions(-)

 46182 files changed, 18604824 deletions(-)

 46278 files changed, 18709249 deletions(-)

 46261 files changed, 18661257 deletions(-)

 46257 files changed, 18661798 deletions(-)

 46202 files changed, 18623329 deletions(-)

 46182 files changed, 18604624 deletions(-)

 46182 files changed, 18604824 deletions(-)

 46278 files changed, 18709556 deletions(-)

 46268 files changed, 18699553 deletions(-)

 46207 files changed, 18614501 deletions(-)

 46260 files changed, 18661840 deletions(-)

 46182 files changed, 18604624 deletions(-)

 46182 files changed, 18604818 deletions(-)

 46244 files changed, 18650899 deletions(-)

 46270 files changed, 18700076 deletions(-)

 46241 files changed, 18649444 deletions(-)

 46271 files changed, 18700807 deletions(-)

 46182 files changed, 18604624 deletions(-)

 46244 files changed, 18650899 deletions(-)

 46182 files changed, 18604818 deletions(-)

 46277 files changed, 18708713 deletions(-)

 46255 files changed, 18658211 deletions(-)

 46271 files changed, 18701043 deletions(-)

 46182 files changed, 18604689 deletions(-)

 46258 files changed, 18658703 deletions(-)

 46182 files changed, 18604884 deletions(-)

 46278 files changed, 18709139 deletions(-)

 46255 files changed, 18658450 deletions(-)

 46271 files changed, 18703520 deletions(-)

 46182 files changed, 18604689 deletions(-)

 46182 files changed, 18604902 deletions(-)

 46257 files changed, 18659492 deletions(-)

 46278 files changed, 18709685 deletions(-)

 46258 files changed, 18658722 deletions(-)

 46272 files changed, 18709261 deletions(-)

 46182 files changed, 18604685 deletions(-)

 46182 files changed, 18604902 deletions(-)

 46257 files changed, 18659852 deletions(-)

 46258 files changed, 18658624 deletions(-)

 46257 files changed, 18659396 deletions(-)

 46273 files changed, 18710464 deletions(-)

 46182 files changed, 18604745 deletions(-)

 46257 files changed, 18659885 deletions(-)

 46182 files changed, 18604903 deletions(-)

 46257 files changed, 18659931 deletions(-)

 46257 files changed, 18660316 deletions(-)

 46336 files changed, 18726268 deletions(-)

 46182 files changed, 18604745 deletions(-)

 46182 files changed, 18604913 deletions(-)

 46257 files changed, 18660046 deletions(-)

 46257 files changed, 18660231 deletions(-)

 46257 files changed, 18660316 deletions(-)

 46340 files changed, 18726738 deletions(-)

 46182 files changed, 18604745 deletions(-)

 46182 files changed, 18605460 deletions(-)

 46257 files changed, 18660083 deletions(-)

 46257 files changed, 18660359 deletions(-)

 46257 files changed, 18660425 deletions(-)

 46074 files changed, 18558153 deletions(-)

steve@sspencer10:/1TB_HDD/Sean/caf/caf_msm-3.10$`
```

**Comment by cybojenix** [comment]
OK, something strange is happening there. It's not outputting additions. 
Maybe there aren't any, but that seems unlikely. 

I'll fetch the repository at the weekend and do some testing

**Comment by deadman96385** [comment]
Sounds good thanks

**Comment by deadman96385** [comment]
Any luck?

**Comment by cbtc** [comment]
Any new @cybojenix ?

**Comment by vinecodes** [comment]
Any progress regarding this? @deadman96385 @cybojenix

**Comment by vinecodes** [comment]
Fixed it. @deadman96385 @cybojenix 

https://github.com/luca020400/dotfiles/issues/1
